server:
  port: 8080


spring:
  messages:
    basename: messages
    encoding: UTF-8
  profile:
    active: local
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  mvc:
    static-path-pattern: /static/**
    hidden-method:
      filter:
        enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/order1
    username: root
    password: 1234

  jpa:
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mariadb://localhost:3306/order1
    user: root
    password: 1234

  redis:
    host: 127.0.0.1
    port: 6379

  logging:
    config: classpath:logback.xml